# Generated by Django 4.2 on 2023-04-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requestLogger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=132)),
                ("action_type", models.CharField(blank=True, max_length=16, null=True)),
                ("instance_pk", models.IntegerField(blank=True, null=True)),
                ("changes", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
